name: Release Automation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y patchelf zip



      - name: Extract version number
        id: extract_version
        run: |
          VERSION=$(grep IMAGE_VERSION Dockerfile | head -n 1 | awk -F '=' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract coraza version number
        id: extract_coraza_version
        run: |
          CORAZA_VERSION=$(grep  CORAZA_VERSION Dockerfile | head -n 1 | awk -F '=' '{print $2}')
          echo "CORAZA_VERSION=$CORAZA_VERSION" >> $GITHUB_ENV

      - name: Extract apisix version number
        id: extract_apisix_version
        run: |
          APISIX_VERSION=$(grep  APISIX_VERSION Dockerfile | head -n 1 | awk -F '=' '{print $2}')
          echo "APISIX_VERSION=$APISIX_VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/apisix-coraza:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/apisix-coraza:latest

      - name: Create release notes
        id: generate_notes
        run: |
          echo "# APISIX-CORAZA Version: $VERSION" > release_notes.md
          echo "## APISIX Version: $APISIX_VERSION" >> release_notes.md
          echo "## Coraza Wasm Plugin Version: $CORAZA_VERSION" >> release_notes.md

      - name: Create apisix-coraza.zip
        run: |
          zip -r apisix-coraza.zip . -x ".git/*" ".github/*"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          body_path: ./release_notes.md
          files: |
            apisix-coraza.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
